Modified brightness script and added new brightness-up/down scripts

diff --git a/.local/bin/brightness b/.local/bin/brightness
--- a/.local/bin/brightness
+++ b/.local/bin/brightness
@@ -1,9 +1,10 @@
 #!/bin/sh
+# Script to set brightness to a given percent
 
-LEVEL=$1
-[ $LEVEL -gt 100 -o $LEVEL -lt 0 ] && echo "Error: input a brightness value in the range 0, 100" && exit 1
-
-brightness_level="$(( $LEVEL / 100)).$(( $LEVEL % 100 ))"
 screenname=$(xrandr | grep " connected" | cut -f1 -d" ")
-xrandr --output $screenname --brightness $brightness_level
-echo -e "Screen $screenname's brightness level set to" $LEVEL"%"
+
+[ $1 -gt 100 -o $1 -lt 0 ] && echo "Error: input a brightness value in the range 0, 100" && exit 1
+new="$(($1 / 100)).$(($1 % 100))"
+xrandr --output $screenname --brightness $new
+
+echo -e "Screen $screenname's brightness level set to" $new"%"
