Fixese to brightness scripts + made mappings for them in i3

diff --git a/.local/bin/brightness b/.local/bin/brightness
--- a/.local/bin/brightness
+++ b/.local/bin/brightness
@@ -1,10 +1,11 @@
 #!/bin/sh
 # Script to set brightness to a given percent
 
-screenname=$(xrandr | grep " connected" | cut -f1 -d" ")
+[ -z "$1" ] && echo "Missing argument for brightness level" && exit 1
 
+screenname=$(xrandr | grep " connected" | cut -d " " -f 1)
 [ $1 -gt 100 -o $1 -lt 0 ] && echo "Error: input a brightness value in the range 0, 100" && exit 1
 new="$(($1 / 100)).$(($1 % 100))"
 xrandr --output $screenname --brightness $new
 
-echo -e "Screen $screenname's brightness level set to" $new"%"
+echo -e "Screen $screenname's brightness level set to" $new""
