Merged brightness scripts into one taking flags for each function

diff --git a/.local/bin/brightness b/.local/bin/brightness
--- a/.local/bin/brightness
+++ b/.local/bin/brightness
@@ -1,11 +1,46 @@
 #!/bin/sh
 # Script to set brightness to a given percent
+usage="USAGE: brightness [OPTION]
+Change active screens brightness. Screen brightness values should be in the range 0..1
 
-[ -z "$1" ] && echo "Missing argument for brightness level" && exit 1
+Options:
+  -s, --set=NUM           set screen brightness to NUM
+  -i, --increment=NUM     increment screen brightness by NUM, default 0.10
+  -d, --decrement=NUM     decrement screen brightness by NUM, default 0.10"
 
 screenname=$(xrandr | grep " connected" | cut -d " " -f 1)
-[ $1 -gt 100 -o $1 -lt 0 ] && echo "Error: input a brightness value in the range 0, 100" && exit 1
-new="$(($1 / 100)).$(($1 % 100))"
-xrandr --output $screenname --brightness $new
+current=$(xrandr --verbose --current | grep "$screenname" -A5 | tail -n1 | cut -d ":" -f 2)
+[ -z $1 ] && echo "Current brightness level:$current" && exit 1
+for ((i=1; i<=$#; i++)); do
+    case "${!i}" in
+    "--help")
+        echo "$usage"
+        exit 0
+        ;;
+    "-s" | "--set")
+        nextarg=$((i+1))
+        value="${!nextarg}"
+        [ -z "$value" ] && echo "Missing argument for brightness level" && exit 1
 
-echo -e "Screen $screenname's brightness level set to" $new""
+        [[ $value -gt 100 || $value -lt 0 ]] && echo "Error: input a brightness value in the range 0, 100" && exit 1
+        new="$(($value / 100)).$(($value % 100))"
+        xrandr --output $screenname --brightness $new
+
+        echo -e "Screen $screenname's brightness level set to" $new""
+        ;;
+    "-i" | "--increment") 
+        [ $current = "1.0" ] && echo "Brightness already at max (1.0)" && exit 1
+        new="$(echo "$current 0.1" | awk '{printf "%f", $1 + $2}')"
+        xrandr --output $screenname --brightness $new
+
+        echo "Decreased brightness to $new"
+        ;;
+    "-d" | "--decrement")
+        [ $current = "0.10" ] && echo "Brightness already at (0.10)" && exit 1
+        new="$(echo "$current 0.1" | awk '{printf "%f", $1 - $2}')"
+        xrandr --output $screenname --brightness $new
+
+        echo "Decreased brightness to $new"
+        ;;
+    esac
+done
